---
  functional:
    - Возможность создать новую игру
    - Возможность выбрать язык программирования
    - Фильтр по сложности игры
    - Установить время на продолжительность игры
    - Возможность выбрать соперника
    - Виден экран соперника
    - Чат с соперником
    - Видеть описание задачи во время игры
    - Можно отказаться от продолжения игры (сдаться)
    - Сбросить свое решение в процессе игры (начать сначала)
    - Проверить свое решение досрочно (до истечения таймера игры)
    - Нельзя начать новую игру, если уже играешь
  non-functional:
    - При верном вводе логине и пароля пользователь должен войти в систему
    - При неправильном логине или пароле пользователь должен получить сообщение об ошибке
  implicit:
    -
