---
  functional:
    - Возможность создать новую игру
    - Возможность выбрать язык программирования
    - Фильтр по сложности игры
    - Возможность выбрать соперника
    - Виден экран соперника
    - Можно видеть действия соперника
    - Можно отказаться от продолжения игры (сдаться)
    - Сбросить свое решение в процессе игры (начать сначала)
    - 
  non-functional:
    - Сайт должен быть безопасным и защищать данные пользователя
    - 
  implicit:
    - 
    - 
