---
  functional:
    - Возможность создать новую игру
    - Возможность выбрать язык программирования
    - Фильтр по сложности игры
    - Установить время на продолжительность игры
    - Возможность выбрать соперника
    - Виден экран соперника
    - Чат с соперником
    - Видеть описание задачи во время игры
    - Выбрать язык описания задачи (русский-английский)
    - Можно видеть действия соперника
    - Можно отказаться от продолжения игры (сдаться)
    - Сбросить свое решение в процессе игры (начать сначала)
    - Проверить свое решение досрочно (до истечения таймера игры)
    - Перейти на главную страницу в процессе игры, не завершая игру
    - Нельзя начать новую игру, если уже играешь
  non-functional:
    - Сайт должен быть безопасным и защищать данные пользователя
  implicit:
    -
